### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by BerkanYildiz** [frankpaschen99/csgolotus-backend#1]
Hello,

is it possible for you to upload the CSGoLotus.com database structure ? ( Not the data, just the structure for the source )

**Comment by frankpaschen99** [comment]
Ummm im pretty sure it was just a single table to store users,  one column for the STEAMID64 and one for the date registered.

The STEAMID64 mightve been DECIMAL(17) and the date registered was a DATETIME

**Comment by frankpaschen99** [comment]
If you dont mind me asking, why on earth are you interested in this piece of crap?
